<?php
// Register ACF local field groups for Products and Certification taxonomy.

if (! defined('ABSPATH')) { exit; }

add_action('acf/init', function () {
  if (! function_exists('acf_add_local_field_group')) { return; }

  // ── Product Data (Feed) ────────────────────────────────────────────────────
  acf_add_local_field_group([
    'key'    => 'group_gc_product_data',
    'title'  => 'Product Data (Feed)',
    'fields' => [

      // ── 1 · Schlüssel / Zuordnung ──────────────────────────────────────────
      [ 'key' => 'tab_identifiers', 'label' => 'Schlüssel / Zuordnung', 'type' => 'tab', 'placement' => 'top' ],
      [ 'key' => 'field_external_id', 'label' => 'External ID', 'name' => 'external_id', 'type' => 'text',
        'instructions' => 'Unique ID from feed (g:id). Read-only.', 'required' => 1, 'readonly' => 1,
        'wrapper' => ['width' => '33'] ],
      [ 'key' => 'field_gtin', 'label' => 'GTIN', 'name' => 'gtin', 'type' => 'text',
        'instructions' => 'Global Trade Item Number from feed (ean).',
        'wrapper' => ['width' => '33'] ],
      [ 'key' => 'field_product_3digit_mastercode', 'label' => '3-Digit Mastercode', 'name' => 'product_3digit_mastercode', 'type' => 'text',
        'instructions' => 'Three-digit internal mastercode.',
        'wrapper' => ['width' => '34'] ],
      [ 'key' => 'field_source_link', 'label' => 'Source Link', 'name' => 'source_link', 'type' => 'url',
        'instructions' => 'Original product link from feed.' ],
      [ 'key' => 'field_artno_list', 'label' => 'Article Numbers', 'name' => 'artno_list',
        'type' => 'repeater', 'layout' => 'table', 'button_label' => 'Add Article Number',
        'instructions' => 'Article numbers from feed (artno_list/artno).',
        'sub_fields' => [
          [ 'key' => 'field_artno_list_artno', 'label' => 'Article No.', 'name' => 'artno', 'type' => 'text' ],
        ],
      ],

      // ── 2 · Corporate Identität ────────────────────────────────────────────
      [ 'key' => 'tab_corporate_identity', 'label' => 'Corporate Identität', 'type' => 'tab' ],
      [ 'key' => 'field_product_model_name', 'label' => 'Model Name', 'name' => 'product_model_name', 'type' => 'text',
        'instructions' => 'From product_info/model_name (e.g., GCAP50).',
        'wrapper' => ['width' => '50'] ],
      [ 'key' => 'field_series', 'label' => 'Series', 'name' => 'series', 'type' => 'text',
        'instructions' => 'Product series from feed (e.g., ECO STAR+).',
        'wrapper' => ['width' => '50'] ],
      [ 'key' => 'field_title_seo', 'label' => 'SEO Title', 'name' => 'title_seo', 'type' => 'text',
        'instructions' => 'SEO-optimized product title from feed.' ],

      // ── 3 · Einsatz & Nutzen ───────────────────────────────────────────────
      [ 'key' => 'tab_use_benefits', 'label' => 'Einsatz & Nutzen', 'type' => 'tab' ],
      [ 'key' => 'field_use_cases', 'label' => 'Use Cases', 'name' => 'use_cases',
        'type' => 'repeater', 'layout' => 'table', 'button_label' => 'Add Use Case',
        'instructions' => 'Use cases from feed (use_cases/use_case).',
        'sub_fields' => [
          [ 'key' => 'field_use_case_text', 'label' => 'Text', 'name' => 'text', 'type' => 'text' ],
        ],
      ],
      [ 'key' => 'field_benefits', 'label' => 'Benefits', 'name' => 'benefits',
        'type' => 'repeater', 'layout' => 'table', 'button_label' => 'Add Benefit',
        'instructions' => 'Product benefits from feed (benefits/benefit).',
        'sub_fields' => [
          [ 'key' => 'field_benefit_text', 'label' => 'Text', 'name' => 'text', 'type' => 'text' ],
        ],
      ],

      // ── 4 · Corporate Texte ────────────────────────────────────────────────
      [ 'key' => 'tab_corporate_texts', 'label' => 'Corporate Texte', 'type' => 'tab' ],
      [ 'key' => 'field_intro', 'label' => 'Intro', 'name' => 'intro', 'type' => 'textarea', 'new_lines' => 'wpautop',
        'instructions' => 'Intro text from feed (intro).',
        'wrapper' => ['width' => '100'] ],
      [ 'key' => 'field_legal_notice', 'label' => 'Legal Notice', 'name' => 'legal_notice', 'type' => 'textarea', 'new_lines' => 'wpautop',
        'instructions' => 'Legal notice from feed (legal_notice).',
        'wrapper' => ['width' => '100'] ],

      // ── 5 · Medien ─────────────────────────────────────────────────────────
      [ 'key' => 'tab_media', 'label' => 'Medien', 'type' => 'tab' ],
      [ 'key' => 'field_additional_image_links', 'label' => 'Additional Images', 'name' => 'additional_image_links',
        'type' => 'gallery', 'return_format' => 'id', 'preview_size' => 'thumbnail', 'insert' => 'append',
        'instructions' => 'Additional product images from feed.',
        'wrapper' => ['width' => '100'] ],
      [ 'key' => 'field_videos', 'label' => 'Videos', 'name' => 'videos',
        'type' => 'repeater', 'layout' => 'block', 'button_label' => 'Add Video',
        'instructions' => 'Multiple videos per product (feed path: video/youtube_id).',
        'sub_fields' => [
          [ 'key' => 'field_video_title', 'label' => 'Title', 'name' => 'title', 'type' => 'text',
            'instructions' => 'Optional title for this video.',
            'wrapper' => ['width' => '40'] ],
          [ 'key' => 'field_video_youtube_id', 'label' => 'YouTube ID', 'name' => 'youtube_id', 'type' => 'text',
            'instructions' => 'YouTube video ID (e.g. dQw4w9WgXcQ).',
            'wrapper' => ['width' => '30'] ],
          [ 'key' => 'field_video_file', 'label' => 'Video File', 'name' => 'video_file',
            'type' => 'file', 'return_format' => 'id', 'library' => 'all',
            'instructions' => 'Optional upload from Media Library.',
            'wrapper' => ['width' => '30'] ],
        ] ],

      // ── 6 · Technische Daten ───────────────────────────────────────────────
      [ 'key' => 'tab_tech', 'label' => 'Technische Daten', 'type' => 'tab' ],

      // Technik
      [ 'key' => 'field_doors', 'label' => 'Doors', 'name' => 'doors', 'type' => 'text', 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_door_type', 'label' => 'Door Type', 'name' => 'door_type', 'type' => 'text', 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_reversible_door', 'label' => 'Reversible Door', 'name' => 'reversible_door', 'type' => 'text', 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_interior_lighting', 'label' => 'Interior Lighting', 'name' => 'interior_lighting', 'type' => 'text', 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_coolant', 'label' => 'Coolant', 'name' => 'coolant', 'type' => 'text', 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_functions', 'label' => 'Functions', 'name' => 'functions', 'type' => 'text', 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_climate_class', 'label' => 'Climate Class', 'name' => 'climate_class', 'type' => 'text', 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_controller', 'label' => 'Controller', 'name' => 'controller', 'type' => 'text', 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_shelves_raw', 'label' => 'Shelves', 'name' => 'shelves_raw', 'type' => 'text', 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_material_inside', 'label' => 'Material (inside)', 'name' => 'material_inside', 'type' => 'text', 'wrapper' => ['width' => '50'] ],
      [ 'key' => 'field_electrical_connection', 'label' => 'Electrical Connection', 'name' => 'electrical_connection', 'type' => 'text', 'wrapper' => ['width' => '50'] ],
      [ 'key' => 'field_properties_durchmesser', 'label' => 'Durchmesser', 'name' => 'properties_durchmesser', 'type' => 'text',
        'instructions' => 'Diameter from feed (properties_durchmesser).',
        'wrapper' => ['width' => '50'] ],

      // Temperatur
      [ 'key' => 'field_temperature_range_raw', 'label' => 'Temperature Range (raw)', 'name' => 'temperature_range_raw', 'type' => 'text',
        'instructions' => 'Original string, e.g. "0 °C / 10 °C".',
        'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_temp_from_c', 'label' => 'Temp From (°C)', 'name' => 'temp_from_c', 'type' => 'number', 'step' => 0.1, 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_temp_till_c', 'label' => 'Temp Till (°C)', 'name' => 'temp_till_c', 'type' => 'number', 'step' => 0.1, 'wrapper' => ['width' => '33.3'] ],

      // Abmessungen & Volumen
      [ 'key' => 'field_width_mm', 'label' => 'Width (mm)', 'name' => 'width_mm', 'type' => 'number', 'step' => 1, 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_height_mm', 'label' => 'Height (mm)', 'name' => 'height_mm', 'type' => 'number', 'step' => 1, 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_depth_mm', 'label' => 'Depth (mm)', 'name' => 'depth_mm', 'type' => 'number', 'step' => 1, 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_hxwxd_inside_raw', 'label' => 'HxWxD Inside (raw)', 'name' => 'hxwxd_inside_raw', 'type' => 'text', 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_hxwxd_outside_raw', 'label' => 'HxWxD Outside (raw)', 'name' => 'hxwxd_outside_raw', 'type' => 'text', 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_volume_l', 'label' => 'Volume (l)', 'name' => 'volume_l', 'type' => 'number', 'step' => 0.1, 'wrapper' => ['width' => '16.6'] ],
      [ 'key' => 'field_volume_raw', 'label' => 'Volume (raw)', 'name' => 'volume_raw', 'type' => 'text', 'wrapper' => ['width' => '16.6'] ],

      // Gewicht & Lautstärke
      [ 'key' => 'field_net_weight_kg', 'label' => 'Net Weight (kg)', 'name' => 'net_weight_kg', 'type' => 'number', 'step' => 0.01, 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_weight_raw', 'label' => 'Weight (raw)', 'name' => 'weight_raw', 'type' => 'text', 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_noise_volume_db', 'label' => 'Noise (dB)', 'name' => 'noise_volume_db', 'type' => 'number', 'step' => 0.1, 'wrapper' => ['width' => '33.3'] ],

      // Energiewerte
      [ 'key' => 'field_energy_label', 'label' => 'Energy Label', 'name' => 'energy_label', 'type' => 'text',
        'instructions' => 'Energy efficiency class (A–G).',
        'wrapper' => ['width' => '20'] ],
      [ 'key' => 'field_energy_consumption_24h_raw', 'label' => 'Energy Consumption (per 24h, raw)', 'name' => 'energy_consumption_24h_raw', 'type' => 'text',
        'instructions' => 'Original string, e.g. "0,44 kWh / 24h".',
        'wrapper' => ['width' => '30'] ],
      [ 'key' => 'field_energy_consumption_per_year', 'label' => 'Energy Consumption (per year, kWh)', 'name' => 'energy_consumption_per_year', 'type' => 'number', 'step' => 0.01, 'wrapper' => ['width' => '20'] ],
      [ 'key' => 'field_eei_raw', 'label' => 'EEI (raw)', 'name' => 'eei_raw', 'type' => 'text',
        'instructions' => 'Original EEI string, may contain commas (e.g. "43,4").',
        'wrapper' => ['width' => '30'] ],

      // ── 7 · Features ───────────────────────────────────────────────────────
      [ 'key' => 'tab_features', 'label' => 'Features', 'type' => 'tab' ],
      [ 'key' => 'field_features', 'label' => 'Features', 'name' => 'features',
        'type' => 'repeater', 'layout' => 'table', 'button_label' => 'Add Feature',
        'instructions' => 'Product features from feed (features/feature).',
        'sub_fields' => [
          [ 'key' => 'field_feature_text', 'label' => 'Text', 'name' => 'text', 'type' => 'text' ],
        ],
      ],

      // ── 8 · Varianten ──────────────────────────────────────────────────────
      [ 'key' => 'tab_variants', 'label' => 'Varianten', 'type' => 'tab' ],
      [ 'key' => 'field_variants', 'label' => 'Variant Groups', 'name' => 'variants',
        'type' => 'repeater', 'layout' => 'block', 'button_label' => 'Add Variant Group',
        'instructions' => 'Variant groups from feed (variants/variant_group).',
        'sub_fields' => [
          [ 'key' => 'field_variant_base_model',     'label' => 'Base Model',     'name' => 'base_model',     'type' => 'text', 'wrapper' => ['width' => '25'] ],
          [ 'key' => 'field_variant_can_size',        'label' => 'Can Size',       'name' => 'can_size',       'type' => 'text', 'wrapper' => ['width' => '25'] ],
          [ 'key' => 'field_variant_capacity',        'label' => 'Capacity',       'name' => 'capacity',       'type' => 'text', 'wrapper' => ['width' => '25'] ],
          [ 'key' => 'field_variant_volume',          'label' => 'Volume',         'name' => 'volume',         'type' => 'text', 'wrapper' => ['width' => '25'] ],
          [ 'key' => 'field_variant_color_body',      'label' => 'Gehäuse-Farbe',  'name' => 'color_body',     'type' => 'text', 'wrapper' => ['width' => '33'] ],
          [ 'key' => 'field_variant_color_canopy',    'label' => 'Hauben-Farbe',   'name' => 'color_canopy',   'type' => 'text', 'wrapper' => ['width' => '33'] ],
          [ 'key' => 'field_variant_interior_color',  'label' => 'Innenfarbe',     'name' => 'interior_color', 'type' => 'text', 'wrapper' => ['width' => '33'] ],
          [ 'key' => 'field_variant_description',     'label' => 'Description',    'name' => 'description',    'type' => 'textarea', 'new_lines' => 'br', 'wrapper' => ['width' => '100'] ],
          [ 'key' => 'field_variant_options', 'label' => 'Options', 'name' => 'options',
            'type' => 'repeater', 'layout' => 'table', 'button_label' => 'Add Option',
            'sub_fields' => [
              [ 'key' => 'field_variant_option_artno',           'label' => 'Article No.',     'name' => 'artno',           'type' => 'text' ],
              [ 'key' => 'field_variant_option_type',            'label' => 'Type',            'name' => 'type',            'type' => 'text' ],
              [ 'key' => 'field_variant_option_value',           'label' => 'Value',           'name' => 'value',           'type' => 'text' ],
              [ 'key' => 'field_variant_option_ean',             'label' => 'EAN',             'name' => 'ean',             'type' => 'text' ],
              [ 'key' => 'field_variant_option_energylabel',     'label' => 'Energieklasse',   'name' => 'energylabel',     'type' => 'text' ],
              [ 'key' => 'field_variant_option_link',            'label' => 'Link',            'name' => 'link',            'type' => 'url'  ],
              [ 'key' => 'field_variant_option_additional_info', 'label' => 'Additional Info', 'name' => 'additional_info', 'type' => 'text' ],
              [ 'key' => 'field_variant_option_image_link', 'label' => 'Image Link', 'name' => 'image_link', 'type' => 'image', 'return_format' => 'array', 'preview_size' => 'thumbnail' ],
            ],
          ],
        ],
      ],

      // ── 9 · Kapazitäten ────────────────────────────────────────────────────
      [ 'key' => 'tab_capacity', 'label' => 'Kapazitäten', 'type' => 'tab' ],
      [ 'key' => 'field_capacity_bottles_033', 'label' => 'Bottles 0,33l', 'name' => 'bottles_033',
        'type' => 'text', 'instructions' => 'Feed path: capacities/bottles_033.', 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_capacity_bottles_050', 'label' => 'Bottles 0,50l', 'name' => 'bottles_050',
        'type' => 'text', 'instructions' => 'Feed path: capacities/bottles_050.', 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_capacity_bottles_070', 'label' => 'Bottles 0,70l', 'name' => 'bottles_070',
        'type' => 'text', 'instructions' => 'Feed path: capacities/bottles_070.', 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_capacity_cans_025', 'label' => 'Cans 0,25l', 'name' => 'cans_025',
        'type' => 'text', 'instructions' => 'Feed path: capacities/cans_025.', 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_capacity_cans_033', 'label' => 'Cans 0,33l', 'name' => 'cans_033',
        'type' => 'text', 'instructions' => 'Feed path: capacities/cans_033.', 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_capacity_cans_033_slim', 'label' => 'Cans 0,33l Slim', 'name' => 'cans_033_slim',
        'type' => 'text', 'instructions' => 'Feed path: capacities/cans_033_slim.', 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_capacity_cans_033_slim_note', 'label' => 'Cans 0,33l Slim Note', 'name' => 'cans_033_slim_note',
        'type' => 'text', 'instructions' => 'Feed path: capacities/cans_033_slim_note.', 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_capacity_cans_050', 'label' => 'Cans 0,50l', 'name' => 'cans_050',
        'type' => 'text', 'instructions' => 'Feed path: capacities/cans_050.', 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_capacity_bib_capacity', 'label' => 'BIB Capacity', 'name' => 'bib_capacity',
        'type' => 'text', 'instructions' => 'Feed path: capacities/bib_capacity.', 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_capacity_cooler_capacity', 'label' => 'Cooler Capacity', 'name' => 'cooler_capacity',
        'type' => 'text', 'instructions' => 'Feed path: capacities/cooler_capacity.', 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_capacity_dispensers', 'label' => 'Dispensers', 'name' => 'dispensers',
        'type' => 'text', 'instructions' => 'Feed path: capacities/dispensers.', 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_capacity_freezer_capacity', 'label' => 'Freezer Capacity', 'name' => 'freezer_capacity',
        'type' => 'text', 'instructions' => 'Feed path: capacities/freezer_capacity.', 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_capacity_keg_capacity', 'label' => 'Keg Capacity', 'name' => 'keg_capacity',
        'type' => 'text', 'instructions' => 'Feed path: capacities/keg_capacity.', 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_capacity_portions_050l', 'label' => 'Portions 0,50l', 'name' => 'portions_050l',
        'type' => 'text', 'instructions' => 'Feed path: capacities/portions_050l.', 'wrapper' => ['width' => '33.3'] ],

      // ── 10 · Zertifizierung ────────────────────────────────────────────────
      [ 'key' => 'tab_certification', 'label' => 'Zertifizierung', 'type' => 'tab' ],
      [ 'key' => 'field_properties_certificates', 'label' => 'Certificates (raw)', 'name' => 'properties_certificates', 'type' => 'text',
        'instructions' => 'From properties/properties_certificates (raw XML value).',
        'wrapper' => ['width' => '100'] ],

      // ── 11 · Produktinfo ───────────────────────────────────────────────────
      [ 'key' => 'tab_product_info', 'label' => 'Produktinfo', 'type' => 'tab' ],
      [ 'key' => 'field_product_info_model_name', 'label' => 'Model Name (product_info)', 'name' => 'product_info_model_name', 'type' => 'text',
        'instructions' => 'From product_info/model_name.',
        'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_product_info_product_3digit_mastercode', 'label' => '3-Digit Mastercode (product_info)', 'name' => 'product_info_product_3digit_mastercode', 'type' => 'text',
        'instructions' => 'From product_info/product_3digit_mastercode.',
        'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_product_info_product_group', 'label' => 'Product Group (raw)', 'name' => 'product_info_product_group', 'type' => 'text',
        'instructions' => 'From product_info/product_group (raw XML value).',
        'wrapper' => ['width' => '33.3'] ],

      // ── 12 · Downloads ─────────────────────────────────────────────────────
      [ 'key' => 'tab_downloads', 'label' => 'Downloads', 'type' => 'tab' ],
      [ 'key' => 'field_datasheets', 'label' => 'Datasheets', 'name' => 'datasheets',
        'type' => 'repeater', 'layout' => 'table', 'button_label' => 'Add Datasheet',
        'instructions' => 'Datasheets from feed (downloads/datasheets/datasheet).',
        'sub_fields' => [
          [ 'key' => 'field_datasheet_title',    'label' => 'Title',    'name' => 'title',    'type' => 'text' ],
          [ 'key' => 'field_datasheet_language', 'label' => 'Language', 'name' => 'language', 'type' => 'text' ],
          [ 'key' => 'field_datasheet_file_url', 'label' => 'File URL', 'name' => 'file_url', 'type' => 'url'  ],
          [ 'key' => 'field_datasheet_file_type', 'label' => 'File Type', 'name' => 'file_type', 'type' => 'text'  ],
          [ 'key' => 'field_datasheet_file_size', 'label' => 'File Size', 'name' => 'file_size', 'type' => 'text'  ],
          [ 'key' => 'field_datasheet_version', 'label' => 'Version', 'name' => 'version', 'type' => 'text'  ],
          [ 'key' => 'field_datasheet_last_updated', 'label' => 'Last Updated', 'name' => 'last_updated', 'type' => 'text'  ],
          [ 'key' => 'field_datasheet_file_note', 'label' => 'File Note', 'name' => 'file_note', 'type' => 'text'  ],
        ],
      ],
      [ 'key' => 'field_manuals', 'label' => 'Manuals', 'name' => 'manuals',
        'type' => 'repeater', 'layout' => 'table', 'button_label' => 'Add Manual',
        'instructions' => 'Manuals from feed (downloads/manuals/manual).',
        'sub_fields' => [
          [ 'key' => 'field_manual_title',    'label' => 'Title',    'name' => 'title',    'type' => 'text' ],
          [ 'key' => 'field_manual_language', 'label' => 'Language', 'name' => 'language', 'type' => 'text' ],
          [ 'key' => 'field_manual_file_url', 'label' => 'File URL', 'name' => 'file_url', 'type' => 'url'  ],
          [ 'key' => 'field_manual_file_type', 'label' => 'File Type', 'name' => 'file_type', 'type' => 'text'  ],
          [ 'key' => 'field_manual_file_size', 'label' => 'File Size', 'name' => 'file_size', 'type' => 'text'  ],
          [ 'key' => 'field_manual_version', 'label' => 'Version', 'name' => 'version', 'type' => 'text'  ],
          [ 'key' => 'field_manual_last_updated', 'label' => 'Last Updated', 'name' => 'last_updated', 'type' => 'text'  ],
          [ 'key' => 'field_manual_file_note', 'label' => 'File Note', 'name' => 'file_note', 'type' => 'text'  ],
        ],
      ],
      [ 'key' => 'field_cad_files', 'label' => 'CAD Files', 'name' => 'cad_files',
        'type' => 'repeater', 'layout' => 'table', 'button_label' => 'Add CAD File',
        'instructions' => 'CAD download files from feed (downloads/cad_files/cad_file).',
        'sub_fields' => [
          [ 'key' => 'field_cad_file_title',       'label' => 'Title',       'name' => 'title',       'type' => 'text' ],
          [ 'key' => 'field_cad_file_url',          'label' => 'URL',         'name' => 'url',         'type' => 'url'  ],
          [ 'key' => 'field_cad_file_file_type',    'label' => 'File Type',   'name' => 'file_type',   'type' => 'text' ],
          [ 'key' => 'field_cad_file_file_size',    'label' => 'File Size',   'name' => 'file_size',   'type' => 'text' ],
          [ 'key' => 'field_cad_file_version',      'label' => 'Version',     'name' => 'version',     'type' => 'text' ],
          [ 'key' => 'field_cad_file_last_updated', 'label' => 'Last Updated','name' => 'last_updated','type' => 'text' ],
          [ 'key' => 'field_cad_file_description',  'label' => 'Description', 'name' => 'description', 'type' => 'text' ],
          [ 'key' => 'field_cad_file_format',       'label' => 'Format',      'name' => 'format',      'type' => 'text' ],
        ],
      ],
      [ 'key' => 'field_certificates_downloads', 'label' => 'Certificates Downloads', 'name' => 'certificates_downloads',
        'type' => 'repeater', 'layout' => 'table', 'button_label' => 'Add Certificate Download',
        'instructions' => 'Downloads from feed (downloads/certificates_downloads/*).',
        'sub_fields' => [
          [ 'key' => 'field_certdl_title', 'label' => 'Title', 'name' => 'title', 'type' => 'text' ],
          [ 'key' => 'field_certdl_language', 'label' => 'Language', 'name' => 'language', 'type' => 'text' ],
          [ 'key' => 'field_certdl_file_url', 'label' => 'File URL', 'name' => 'file_url', 'type' => 'url' ],
          [ 'key' => 'field_certdl_file_type', 'label' => 'File Type', 'name' => 'file_type', 'type' => 'text' ],
          [ 'key' => 'field_certdl_file_size', 'label' => 'File Size', 'name' => 'file_size', 'type' => 'text' ],
          [ 'key' => 'field_certdl_version', 'label' => 'Version', 'name' => 'version', 'type' => 'text' ],
          [ 'key' => 'field_certdl_last_updated', 'label' => 'Last Updated', 'name' => 'last_updated', 'type' => 'text' ],
          [ 'key' => 'field_certdl_file_note', 'label' => 'File Note', 'name' => 'file_note', 'type' => 'text' ],
        ],
      ],
      [ 'key' => 'field_installation_guides', 'label' => 'Installation Guides', 'name' => 'installation_guides',
        'type' => 'repeater', 'layout' => 'table', 'button_label' => 'Add Installation Guide',
        'instructions' => 'Downloads from feed (downloads/installation_guides/*).',
        'sub_fields' => [
          [ 'key' => 'field_instguide_title', 'label' => 'Title', 'name' => 'title', 'type' => 'text' ],
          [ 'key' => 'field_instguide_language', 'label' => 'Language', 'name' => 'language', 'type' => 'text' ],
          [ 'key' => 'field_instguide_file_url', 'label' => 'File URL', 'name' => 'file_url', 'type' => 'url' ],
          [ 'key' => 'field_instguide_file_type', 'label' => 'File Type', 'name' => 'file_type', 'type' => 'text' ],
          [ 'key' => 'field_instguide_file_size', 'label' => 'File Size', 'name' => 'file_size', 'type' => 'text' ],
          [ 'key' => 'field_instguide_version', 'label' => 'Version', 'name' => 'version', 'type' => 'text' ],
          [ 'key' => 'field_instguide_last_updated', 'label' => 'Last Updated', 'name' => 'last_updated', 'type' => 'text' ],
          [ 'key' => 'field_instguide_file_note', 'label' => 'File Note', 'name' => 'file_note', 'type' => 'text' ],
        ],
      ],
      [ 'key' => 'field_other_documents', 'label' => 'Other Documents', 'name' => 'other_documents',
        'type' => 'repeater', 'layout' => 'table', 'button_label' => 'Add Other Document',
        'instructions' => 'Downloads from feed (downloads/other_documents/*).',
        'sub_fields' => [
          [ 'key' => 'field_otherdoc_title', 'label' => 'Title', 'name' => 'title', 'type' => 'text' ],
          [ 'key' => 'field_otherdoc_language', 'label' => 'Language', 'name' => 'language', 'type' => 'text' ],
          [ 'key' => 'field_otherdoc_file_url', 'label' => 'File URL', 'name' => 'file_url', 'type' => 'url' ],
          [ 'key' => 'field_otherdoc_file_type', 'label' => 'File Type', 'name' => 'file_type', 'type' => 'text' ],
          [ 'key' => 'field_otherdoc_file_size', 'label' => 'File Size', 'name' => 'file_size', 'type' => 'text' ],
          [ 'key' => 'field_otherdoc_version', 'label' => 'Version', 'name' => 'version', 'type' => 'text' ],
          [ 'key' => 'field_otherdoc_last_updated', 'label' => 'Last Updated', 'name' => 'last_updated', 'type' => 'text' ],
          [ 'key' => 'field_otherdoc_file_note', 'label' => 'File Note', 'name' => 'file_note', 'type' => 'text' ],
        ],
      ],

      // ── 11 · Logistik ──────────────────────────────────────────────────────
      [ 'key' => 'tab_logistics', 'label' => 'Logistik', 'type' => 'tab' ],
      [ 'key' => 'field_shipping_weight_kg', 'label' => 'Shipping Weight (kg)', 'name' => 'shipping_weight_kg',
        'type' => 'number', 'step' => 0.01, 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_pallet_size', 'label' => 'Pallet Size', 'name' => 'pallet_size',
        'type' => 'text', 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_warehouse', 'label' => 'Warehouse', 'name' => 'warehouse',
        'type' => 'text', 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_length_cm', 'label' => 'Shipping Length (mm)', 'name' => 'length_cm',
        'type' => 'number', 'step' => 0.1, 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_width_cm', 'label' => 'Shipping Width (mm)', 'name' => 'width_cm',
        'type' => 'number', 'step' => 0.1, 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_height_cm', 'label' => 'Shipping Height (mm)', 'name' => 'height_cm',
        'type' => 'number', 'step' => 0.1, 'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_shipping_amount_80x60', 'label' => 'Amount / Pallet 80×60', 'name' => 'shipping_amount_80x60',
        'type' => 'number', 'step' => 1, 'wrapper' => ['width' => '20'] ],
      [ 'key' => 'field_shipping_amount_120x80', 'label' => 'Amount / Pallet 120×80', 'name' => 'shipping_amount_120x80',
        'type' => 'number', 'step' => 1, 'wrapper' => ['width' => '20'] ],
      [ 'key' => 'field_shipping_amount_145x100', 'label' => 'Amount / Pallet 145×100', 'name' => 'shipping_amount_145x100',
        'type' => 'number', 'step' => 1, 'wrapper' => ['width' => '20'] ],
      [ 'key' => 'field_shipping_amount_20ft', 'label' => 'Amount / 20ft Container', 'name' => 'shipping_amount_20ft',
        'type' => 'number', 'step' => 1, 'wrapper' => ['width' => '20'] ],
      [ 'key' => 'field_shipping_amount_40ft', 'label' => 'Amount / 40ft HQ Container', 'name' => 'shipping_amount_40ft',
        'type' => 'number', 'step' => 1, 'wrapper' => ['width' => '20'] ],
      [ 'key' => 'field_gc_shipment_storage_40fthqcon', 'label' => 'Shipment Storage (40ft HQ CON, legacy)', 'name' => 'gc_shipment_storage_40fthqcon',
        'type' => 'number', 'step' => 1, 'instructions' => 'Legacy field mapped from shipping_amount_40fthq.',
        'wrapper' => ['width' => '100'] ],

      // ── 12 · Verwendungszweck ──────────────────────────────────────────────
      [ 'key' => 'tab_flags', 'label' => 'Verwendungszweck', 'type' => 'tab' ],
      [ 'key' => 'field_cust_commercialuse', 'label' => 'Commercial Use', 'name' => 'cust_commercialuse',
        'type' => 'true_false', 'ui' => 1, 'wrapper' => ['width' => '25'] ],
      [ 'key' => 'field_cust_gc_householdapp', 'label' => 'Household Appliance', 'name' => 'cust_gc_householdapp',
        'type' => 'true_false', 'ui' => 1, 'wrapper' => ['width' => '25'] ],
      [ 'key' => 'field_cust_gc_bevcooler', 'label' => 'Beverage Cooler', 'name' => 'cust_gc_bevcooler',
        'type' => 'true_false', 'ui' => 1, 'wrapper' => ['width' => '25'] ],
      [ 'key' => 'field_buildin', 'label' => 'Built-in', 'name' => 'buildin',
        'type' => 'true_false', 'ui' => 1, 'wrapper' => ['width' => '25'] ],
      [ 'key' => 'field_convection_cooling', 'label' => 'Convection Cooling', 'name' => 'convection_cooling',
        'type' => 'text', 'instructions' => 'Raw value from feed (e.g. Ja, Nein, Umluftkühlung).',
        'wrapper' => ['width' => '50'] ],
      [ 'key' => 'field_cust_gc_product_capacity', 'label' => 'Has Capacity Data', 'name' => 'cust_gc_product_capacity',
        'type' => 'true_false', 'ui' => 1, 'instructions' => 'Set by importer when capacity data is present.',
        'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_cust_gc_product_capacity_cans', 'label' => 'Has Can Capacities', 'name' => 'cust_gc_product_capacity_cans',
        'type' => 'true_false', 'ui' => 1, 'instructions' => 'Set by importer when can capacities are present.',
        'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_cust_gc_product_capacity_bottles', 'label' => 'Has Bottle Capacities', 'name' => 'cust_gc_product_capacity_bottles',
        'type' => 'true_false', 'ui' => 1, 'instructions' => 'Set by importer when bottle capacities are present.',
        'wrapper' => ['width' => '33.3'] ],

      // ── 13 · Energie-Label ─────────────────────────────────────────────────
      [ 'key' => 'tab_energy_label', 'label' => 'Energie-Label', 'type' => 'tab' ],
      [ 'key' => 'field_cust_gc_eprel', 'label' => 'EPREL Code', 'name' => 'cust_gc_eprel', 'type' => 'text',
        'instructions' => 'EPREL registry code from feed.',
        'wrapper' => ['width' => '33.3'] ],
      [ 'key' => 'field_energy_label_tooltip', 'label' => 'Energy Label Tooltip URL', 'name' => 'energy_label_tooltip', 'type' => 'url',
        'instructions' => 'Link to energy label image.',
        'wrapper' => ['width' => '66.6'] ],
      [ 'key' => 'field_energy_button_html', 'label' => 'Energy Button (HTML)', 'name' => 'energy_button_html',
        'type' => 'textarea', 'new_lines' => 'br',
        'instructions' => 'HTML snippet to display energy label button.',
        'wrapper' => ['width' => '100'] ],

    ],
    'location' => [[[
      'param'    => 'post_type',
      'operator' => '==',
      'value'    => 'product',
    ]]],
    'position' => 'normal',
    'active'   => true,
  ]);

  // ── Certification Term (taxonomy term meta) ────────────────────────────────
  acf_add_local_field_group([
    'key'    => 'group_gc_certification_term',
    'title'  => 'Certification Term',
    'fields' => [
      [
        'key'          => 'field_cert_code',
        'label'        => 'Certification Code',
        'name'         => 'cert_code',
        'type'         => 'text',
        'instructions' => 'Stores the certification code (from g:certification_code).',
      ],
    ],
    'location' => [[[
      'param'    => 'taxonomy',
      'operator' => '==',
      'value'    => 'certification',
    ]]],
    'position' => 'normal',
    'active'   => true,
  ]);
});
